(ns optical_compute.actor
  "optical_compute clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). Photonic computing / optical matrix-multiply 光電融合.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; PhotonicProcessor
   {:db/ident :optical_compute.PhotonicProcessor/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :optical_compute.PhotonicProcessor/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.PhotonicProcessor/platform :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.PhotonicProcessor/topsPerWatt :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.PhotonicProcessor/wavelengths :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.PhotonicProcessor/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.PhotonicProcessor/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; MziMesh
   {:db/ident :optical_compute.MziMesh/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :optical_compute.MziMesh/processorId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.MziMesh/rows :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.MziMesh/columns :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.MziMesh/phaseShifter :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.MziMesh/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.MziMesh/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; OpticalCore
   {:db/ident :optical_compute.OpticalCore/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :optical_compute.OpticalCore/processorId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.OpticalCore/macsPerCycle :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.OpticalCore/precisionBits :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.OpticalCore/clockGhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.OpticalCore/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.OpticalCore/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; NonlinearUnit
   {:db/ident :optical_compute.NonlinearUnit/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :optical_compute.NonlinearUnit/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.NonlinearUnit/activation :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.NonlinearUnit/thresholdMw :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.NonlinearUnit/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.NonlinearUnit/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; WdmBus
   {:db/ident :optical_compute.WdmBus/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :optical_compute.WdmBus/processorId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.WdmBus/channels :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.WdmBus/spacingGhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.WdmBus/aggregateTbps :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.WdmBus/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.WdmBus/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ComputeTile
   {:db/ident :optical_compute.ComputeTile/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :optical_compute.ComputeTile/processorId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.ComputeTile/index :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.ComputeTile/utilization :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.ComputeTile/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.ComputeTile/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :optical_compute.ComputeTile/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"PhotonicProcessor" "MziMesh" "OpticalCore" "NonlinearUnit" "WdmBus" "ComputeTile"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "optical_compute: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "optical_compute: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "optical_compute: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── PhotonicProcessor ────────────────────────────────────────────────────────────────
(defn create-photonic-processor
  "Create a PhotonicProcessor."
  [port data]
  (require-fields data ["name" "platform"])
  (let [id (new-id "opc_pho")
        e {:db/id id
           :optical_compute.PhotonicProcessor/id id
           :optical_compute.PhotonicProcessor/name (get data :name)
           :optical_compute.PhotonicProcessor/platform (get data :platform)
           :optical_compute.PhotonicProcessor/topsPerWatt (as-double (get data :topsPerWatt))
           :optical_compute.PhotonicProcessor/wavelengths (as-long (get data :wavelengths))
           :optical_compute.PhotonicProcessor/createdAt (now)
           :optical_compute.PhotonicProcessor/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-photonic-processors
  "List PhotonicProcessor with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-photonic-processors port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :optical_compute.PhotonicProcessor/id))
         rows (apply-filters rows (:filter opts) [:optical_compute.PhotonicProcessor/name :optical_compute.PhotonicProcessor/platform :optical_compute.PhotonicProcessor/topsPerWatt :optical_compute.PhotonicProcessor/wavelengths])]
     (paginate rows opts))))

(defn get-photonic-processor
  "Retrieve a PhotonicProcessor by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-photonic-processor port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-photonic-processor
  "Update a PhotonicProcessor; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :optical_compute.PhotonicProcessor/name (get data :name)]))
                   (cond-> (contains? data :platform) (conj [:db/add id :optical_compute.PhotonicProcessor/platform (get data :platform)]))
                   (cond-> (contains? data :topsPerWatt) (conj [:db/add id :optical_compute.PhotonicProcessor/topsPerWatt (as-double (get data :topsPerWatt))]))
                   (cond-> (contains? data :wavelengths) (conj [:db/add id :optical_compute.PhotonicProcessor/wavelengths (as-long (get data :wavelengths))]))
                   (conj [:db/add id :optical_compute.PhotonicProcessor/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-photonic-processor
  "Delete a PhotonicProcessor."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── MziMesh ────────────────────────────────────────────────────────────────
(defn create-mzi-mesh
  "Create a MziMesh."
  [port data]
  (require-fields data ["rows" "columns"])
  (let [id (new-id "opc_mzi")
        e {:db/id id
           :optical_compute.MziMesh/id id
           :optical_compute.MziMesh/processorId (get data :processorId)
           :optical_compute.MziMesh/rows (as-long (get data :rows))
           :optical_compute.MziMesh/columns (as-long (get data :columns))
           :optical_compute.MziMesh/phaseShifter (get data :phaseShifter)
           :optical_compute.MziMesh/createdAt (now)
           :optical_compute.MziMesh/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-mzi-meshes
  "List MziMesh with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-mzi-meshes port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :optical_compute.MziMesh/id))
         rows (apply-filters rows (:filter opts) [:optical_compute.MziMesh/processorId :optical_compute.MziMesh/rows :optical_compute.MziMesh/columns :optical_compute.MziMesh/phaseShifter])]
     (paginate rows opts))))

(defn get-mzi-mesh
  "Retrieve a MziMesh by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-mzi-mesh port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-mzi-mesh
  "Update a MziMesh; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :processorId) (conj [:db/add id :optical_compute.MziMesh/processorId (get data :processorId)]))
                   (cond-> (contains? data :rows) (conj [:db/add id :optical_compute.MziMesh/rows (as-long (get data :rows))]))
                   (cond-> (contains? data :columns) (conj [:db/add id :optical_compute.MziMesh/columns (as-long (get data :columns))]))
                   (cond-> (contains? data :phaseShifter) (conj [:db/add id :optical_compute.MziMesh/phaseShifter (get data :phaseShifter)]))
                   (conj [:db/add id :optical_compute.MziMesh/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-mzi-mesh
  "Delete a MziMesh."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── OpticalCore ────────────────────────────────────────────────────────────────
(defn create-optical-core
  "Create a OpticalCore."
  [port data]
  (require-fields data ["macsPerCycle" "precisionBits"])
  (let [id (new-id "opc_opt")
        e {:db/id id
           :optical_compute.OpticalCore/id id
           :optical_compute.OpticalCore/processorId (get data :processorId)
           :optical_compute.OpticalCore/macsPerCycle (as-long (get data :macsPerCycle))
           :optical_compute.OpticalCore/precisionBits (as-long (get data :precisionBits))
           :optical_compute.OpticalCore/clockGhz (as-double (get data :clockGhz))
           :optical_compute.OpticalCore/createdAt (now)
           :optical_compute.OpticalCore/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-optical-cores
  "List OpticalCore with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-optical-cores port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :optical_compute.OpticalCore/id))
         rows (apply-filters rows (:filter opts) [:optical_compute.OpticalCore/processorId :optical_compute.OpticalCore/macsPerCycle :optical_compute.OpticalCore/precisionBits :optical_compute.OpticalCore/clockGhz])]
     (paginate rows opts))))

(defn get-optical-core
  "Retrieve a OpticalCore by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-optical-core port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-optical-core
  "Update a OpticalCore; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :processorId) (conj [:db/add id :optical_compute.OpticalCore/processorId (get data :processorId)]))
                   (cond-> (contains? data :macsPerCycle) (conj [:db/add id :optical_compute.OpticalCore/macsPerCycle (as-long (get data :macsPerCycle))]))
                   (cond-> (contains? data :precisionBits) (conj [:db/add id :optical_compute.OpticalCore/precisionBits (as-long (get data :precisionBits))]))
                   (cond-> (contains? data :clockGhz) (conj [:db/add id :optical_compute.OpticalCore/clockGhz (as-double (get data :clockGhz))]))
                   (conj [:db/add id :optical_compute.OpticalCore/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-optical-core
  "Delete a OpticalCore."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── NonlinearUnit ────────────────────────────────────────────────────────────────
(defn create-nonlinear-unit
  "Create a NonlinearUnit."
  [port data]
  (require-fields data ["activation" "thresholdMw"])
  (let [id (new-id "opc_non")
        e {:db/id id
           :optical_compute.NonlinearUnit/id id
           :optical_compute.NonlinearUnit/coreId (get data :coreId)
           :optical_compute.NonlinearUnit/activation (get data :activation)
           :optical_compute.NonlinearUnit/thresholdMw (as-double (get data :thresholdMw))
           :optical_compute.NonlinearUnit/createdAt (now)
           :optical_compute.NonlinearUnit/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-nonlinear-units
  "List NonlinearUnit with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-nonlinear-units port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :optical_compute.NonlinearUnit/id))
         rows (apply-filters rows (:filter opts) [:optical_compute.NonlinearUnit/coreId :optical_compute.NonlinearUnit/activation :optical_compute.NonlinearUnit/thresholdMw])]
     (paginate rows opts))))

(defn get-nonlinear-unit
  "Retrieve a NonlinearUnit by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-nonlinear-unit port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-nonlinear-unit
  "Update a NonlinearUnit; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :optical_compute.NonlinearUnit/coreId (get data :coreId)]))
                   (cond-> (contains? data :activation) (conj [:db/add id :optical_compute.NonlinearUnit/activation (get data :activation)]))
                   (cond-> (contains? data :thresholdMw) (conj [:db/add id :optical_compute.NonlinearUnit/thresholdMw (as-double (get data :thresholdMw))]))
                   (conj [:db/add id :optical_compute.NonlinearUnit/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-nonlinear-unit
  "Delete a NonlinearUnit."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── WdmBus ────────────────────────────────────────────────────────────────
(defn create-wdm-bus
  "Create a WdmBus."
  [port data]
  (require-fields data ["channels" "spacingGhz"])
  (let [id (new-id "opc_wdm")
        e {:db/id id
           :optical_compute.WdmBus/id id
           :optical_compute.WdmBus/processorId (get data :processorId)
           :optical_compute.WdmBus/channels (as-long (get data :channels))
           :optical_compute.WdmBus/spacingGhz (as-double (get data :spacingGhz))
           :optical_compute.WdmBus/aggregateTbps (as-double (get data :aggregateTbps))
           :optical_compute.WdmBus/createdAt (now)
           :optical_compute.WdmBus/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-wdm-buses
  "List WdmBus with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-wdm-buses port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :optical_compute.WdmBus/id))
         rows (apply-filters rows (:filter opts) [:optical_compute.WdmBus/processorId :optical_compute.WdmBus/channels :optical_compute.WdmBus/spacingGhz :optical_compute.WdmBus/aggregateTbps])]
     (paginate rows opts))))

(defn get-wdm-bus
  "Retrieve a WdmBus by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-wdm-bus port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-wdm-bus
  "Update a WdmBus; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :processorId) (conj [:db/add id :optical_compute.WdmBus/processorId (get data :processorId)]))
                   (cond-> (contains? data :channels) (conj [:db/add id :optical_compute.WdmBus/channels (as-long (get data :channels))]))
                   (cond-> (contains? data :spacingGhz) (conj [:db/add id :optical_compute.WdmBus/spacingGhz (as-double (get data :spacingGhz))]))
                   (cond-> (contains? data :aggregateTbps) (conj [:db/add id :optical_compute.WdmBus/aggregateTbps (as-double (get data :aggregateTbps))]))
                   (conj [:db/add id :optical_compute.WdmBus/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-wdm-bus
  "Delete a WdmBus."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ComputeTile ────────────────────────────────────────────────────────────────
(defn create-compute-tile
  "Create a ComputeTile."
  [port data]
  (require-fields data ["index" "utilization"])
  (let [id (new-id "opc_com")
        e {:db/id id
           :optical_compute.ComputeTile/id id
           :optical_compute.ComputeTile/processorId (get data :processorId)
           :optical_compute.ComputeTile/index (as-long (get data :index))
           :optical_compute.ComputeTile/utilization (as-double (get data :utilization))
           :optical_compute.ComputeTile/status (get data :status)
           :optical_compute.ComputeTile/createdAt (now)
           :optical_compute.ComputeTile/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-compute-tiles
  "List ComputeTile with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-compute-tiles port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :optical_compute.ComputeTile/id))
         rows (apply-filters rows (:filter opts) [:optical_compute.ComputeTile/processorId :optical_compute.ComputeTile/index :optical_compute.ComputeTile/utilization :optical_compute.ComputeTile/status])]
     (paginate rows opts))))

(defn get-compute-tile
  "Retrieve a ComputeTile by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-compute-tile port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-compute-tile
  "Update a ComputeTile; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :processorId) (conj [:db/add id :optical_compute.ComputeTile/processorId (get data :processorId)]))
                   (cond-> (contains? data :index) (conj [:db/add id :optical_compute.ComputeTile/index (as-long (get data :index))]))
                   (cond-> (contains? data :utilization) (conj [:db/add id :optical_compute.ComputeTile/utilization (as-double (get data :utilization))]))
                   (cond-> (contains? data :status) (conj [:db/add id :optical_compute.ComputeTile/status (get data :status)]))
                   (conj [:db/add id :optical_compute.ComputeTile/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-compute-tile
  "Delete a ComputeTile."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/photonicprocessors" :op :create :entity "PhotonicProcessor"}
   {:method "GET" :path "/v1/photonicprocessors" :op :list :entity "PhotonicProcessor"}
   {:method "GET" :path "/v1/photonicprocessors/:id" :op :get :entity "PhotonicProcessor"}
   {:method "PATCH" :path "/v1/photonicprocessors/:id" :op :update :entity "PhotonicProcessor"}
   {:method "DELETE" :path "/v1/photonicprocessors/:id" :op :delete :entity "PhotonicProcessor"}
   {:method "POST" :path "/v1/mzimeshes" :op :create :entity "MziMesh"}
   {:method "GET" :path "/v1/mzimeshes" :op :list :entity "MziMesh"}
   {:method "GET" :path "/v1/mzimeshes/:id" :op :get :entity "MziMesh"}
   {:method "PATCH" :path "/v1/mzimeshes/:id" :op :update :entity "MziMesh"}
   {:method "DELETE" :path "/v1/mzimeshes/:id" :op :delete :entity "MziMesh"}
   {:method "POST" :path "/v1/opticalcores" :op :create :entity "OpticalCore"}
   {:method "GET" :path "/v1/opticalcores" :op :list :entity "OpticalCore"}
   {:method "GET" :path "/v1/opticalcores/:id" :op :get :entity "OpticalCore"}
   {:method "PATCH" :path "/v1/opticalcores/:id" :op :update :entity "OpticalCore"}
   {:method "DELETE" :path "/v1/opticalcores/:id" :op :delete :entity "OpticalCore"}
   {:method "POST" :path "/v1/nonlinearunits" :op :create :entity "NonlinearUnit"}
   {:method "GET" :path "/v1/nonlinearunits" :op :list :entity "NonlinearUnit"}
   {:method "GET" :path "/v1/nonlinearunits/:id" :op :get :entity "NonlinearUnit"}
   {:method "PATCH" :path "/v1/nonlinearunits/:id" :op :update :entity "NonlinearUnit"}
   {:method "DELETE" :path "/v1/nonlinearunits/:id" :op :delete :entity "NonlinearUnit"}
   {:method "POST" :path "/v1/wdmbuses" :op :create :entity "WdmBus"}
   {:method "GET" :path "/v1/wdmbuses" :op :list :entity "WdmBus"}
   {:method "GET" :path "/v1/wdmbuses/:id" :op :get :entity "WdmBus"}
   {:method "PATCH" :path "/v1/wdmbuses/:id" :op :update :entity "WdmBus"}
   {:method "DELETE" :path "/v1/wdmbuses/:id" :op :delete :entity "WdmBus"}
   {:method "POST" :path "/v1/computetiles" :op :create :entity "ComputeTile"}
   {:method "GET" :path "/v1/computetiles" :op :list :entity "ComputeTile"}
   {:method "GET" :path "/v1/computetiles/:id" :op :get :entity "ComputeTile"}
   {:method "PATCH" :path "/v1/computetiles/:id" :op :update :entity "ComputeTile"}
   {:method "DELETE" :path "/v1/computetiles/:id" :op :delete :entity "ComputeTile"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"photonicprocessors" {:create create-photonic-processor :list list-photonic-processors :get get-photonic-processor :update update-photonic-processor :delete delete-photonic-processor}
   "mzimeshes" {:create create-mzi-mesh :list list-mzi-meshes :get get-mzi-mesh :update update-mzi-mesh :delete delete-mzi-mesh}
   "opticalcores" {:create create-optical-core :list list-optical-cores :get get-optical-core :update update-optical-core :delete delete-optical-core}
   "nonlinearunits" {:create create-nonlinear-unit :list list-nonlinear-units :get get-nonlinear-unit :update update-nonlinear-unit :delete delete-nonlinear-unit}
   "wdmbuses" {:create create-wdm-bus :list list-wdm-buses :get get-wdm-bus :update update-wdm-bus :delete delete-wdm-bus}
   "computetiles" {:create create-compute-tile :list list-compute-tiles :get get-compute-tile :update update-compute-tile :delete delete-compute-tile}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "optical_compute-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
